---
version: '3.5'

services:
  nexus:
    image: jbuncle/nexus-repository-composer
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "127.0.0.2:8082:8081"

  nexus-src:
    image: jbuncle/nexus-repository-composer
    volumes:
      - "nexus-data-src:/nexus-data-src"
    ports:
      - "127.0.0.6:8086:8081"
  
volumes:
  nexus-data:
  nexus-data-src: